In [1]:
%pip install pymysql pandas sqlalchemy matplotlib

Requirement already satisfied: pymysql in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (1.2.3)
Requirement already satisfied: pandas in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (3.1.0)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (2.1.6)
Requirement already satisfied: matplotlib in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (3.11.2)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.6 in .\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd 
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root@localhost:3306/climate_watch")

with engine.connect() as con:
    print("succesful connection")

succesful connection

In [7]:
query = """
select * from globaltemperatures
"""
df = pd.read_sql(query, engine)
display(df.head())

,dt,Land_avg_temp,Land_avg_temp_uncertainty,Land_max_temp,Land_max_temp_unc,Land_min_temp,Land_min_temp_unc,Land_and_oceanavgtemp,Land_and_oceanavgtemp_unc
0,1750-01-01,3.034,3.574,NaN,NaN,NaN,NaN,NaN,NaN
1,1750-02-01,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
2,1750-03-01,5.626,3.076,NaN,NaN,NaN,NaN,NaN,NaN
3,1750-04-01,8.490,2.451,NaN,NaN,NaN,NaN,NaN,NaN
4,1750-05-01,11.573,2.072,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df['dt'] = pd.to_datetime(df['dt'])
df_subset_globtemp = df[df['dt'] > '1979-12-31']
display(df_subset_globtemp.head())
df_subset_globtemp.to_csv("C:/Users/sande/Downloads/subset_globtemp.csv", index=False)

,dt,Land_avg_temp,Land_avg_temp_uncertainty,Land_max_temp,Land_max_temp_unc,Land_min_temp,Land_min_temp_unc,Land_and_oceanavgtemp,Land_and_oceanavgtemp_unc
2760,1980-01-01,2.956,0.087,8.468,0.080,-2.457,0.124,13.812,0.049
2761,1980-02-01,3.652,0.099,9.260,0.129,-1.864,0.115,14.112,0.050
2762,1980-03-01,5.367,0.103,11.240,0.160,-0.379,0.126,14.646,0.052
2763,1980-04-01,8.935,0.106,14.821,0.129,3.109,0.175,15.578,0.052
2764,1980-05-01,11.770,0.089,17.713,0.234,6.131,0.172,16.314,0.050

In [19]:
query = """
select * from temp_by_city
"""
df = pd.read_sql(query, engine)
display(df.head())

           dt  avg_temp  Avg_temp_unc   city  country Latitude longitude
0  1743-11-01     6.068         1.737  Århus  Denmark   57.05N    10.33E
1  1743-12-01       NaN           NaN  Århus  Denmark   57.05N    10.33E
2  1744-01-01       NaN           NaN  Århus  Denmark   57.05N    10.33E
3  1744-02-01       NaN           NaN  Århus  Denmark   57.05N    10.33E
4  1744-03-01       NaN           NaN  Århus  Denmark   57.05N    10.33E

In [20]:
df['dt'] = pd.to_datetime(df['dt'])
df_subset_tempcity = df[df['dt'] > '1979-12-31']
display(df_subset_tempcity.head())
df_subset_tempcity.to_csv("C:/Users/sande/Downloads/subset_tempcity.csv", index=False)

             dt  avg_temp  Avg_temp_unc   city  country Latitude longitude
2834 1980-01-01    -1.850         0.363  Århus  Denmark   57.05N    10.33E
2835 1980-02-01    -2.171         0.377  Århus  Denmark   57.05N    10.33E
2836 1980-03-01     0.625         0.178  Århus  Denmark   57.05N    10.33E
2837 1980-04-01     6.151         0.203  Århus  Denmark   57.05N    10.33E
2838 1980-05-01    11.434         0.226  Århus  Denmark   57.05N    10.33E

In [21]:
query = """
select * from temp_by_major_city
"""
df = pd.read_sql(query, engine)
display(df.head())

,dt,avg_temp,Avg_temp_unc,city,Country,latitude,longitude
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W

In [22]:
df['dt'] = pd.to_datetime(df['dt'])
df_subset_tempmajorcity = df[df['dt'] > '1979-12-31']
display(df_subset_tempmajorcity.head())
df_subset_tempmajorcity.to_csv("C:/Users/sande/Downloads/subset_tempmajorcity.csv", index=False)

,dt,avg_temp,Avg_temp_unc,city,Country,latitude,longitude
1572,1980-01-01,27.409,0.497,Abidjan,Côte D'Ivoire,5.63N,3.23W
1573,1980-02-01,28.192,0.358,Abidjan,Côte D'Ivoire,5.63N,3.23W
1574,1980-03-01,28.303,0.430,Abidjan,Côte D'Ivoire,5.63N,3.23W
1575,1980-04-01,28.284,0.223,Abidjan,Côte D'Ivoire,5.63N,3.23W
1576,1980-05-01,26.709,0.383,Abidjan,Côte D'Ivoire,5.63N,3.23W

In [23]:
query = """
select * from temp_by_country
"""
df = pd.read_sql(query, engine)
display(df.head())

           dt  avg_temp  avg_temp_unc country
0  1743-11-01     4.384         2.294   Åland
1  1743-12-01       NaN           NaN   Åland
2  1744-01-01       NaN           NaN   Åland
3  1744-02-01       NaN           NaN   Åland
4  1744-03-01       NaN           NaN   Åland

In [24]:
df['dt'] = pd.to_datetime(df['dt'])
df_subset_tempcountry = df[df['dt'] > '1979-12-31']
display(df_subset_tempcountry.head())
df_subset_tempcountry.to_csv("C:/Users/sande/Downloads/subset_tempcountry.csv", index=False)

             dt  avg_temp  avg_temp_unc country
2834 1980-01-01    -4.073         0.518   Åland
2835 1980-02-01    -6.484         0.441   Åland
2836 1980-03-01    -3.947         0.466   Åland
2837 1980-04-01     2.928         0.597   Åland
2838 1980-05-01     6.154         0.241   Åland

In [25]:
query = """
select * from temp_by_state
"""
df = pd.read_sql(query, engine)
display(df.head())

           dt  avg_temp  Avg_temp_unc state Country
0  1855-05-01    25.544         1.171  Acre  Brazil
1  1855-06-01    24.228         1.103  Acre  Brazil
2  1855-07-01    24.371         1.044  Acre  Brazil
3  1855-08-01    25.427         1.073  Acre  Brazil
4  1855-09-01    25.675         1.014  Acre  Brazil

In [26]:
df['dt'] = pd.to_datetime(df['dt'])
df_subset_tempstate = df[df['dt'] > '1979-12-31']
display(df_subset_tempstate.head())
df_subset_tempstate.to_csv("C:/Users/sande/Downloads/subset_tempstate.csv", index=False)

             dt  avg_temp  Avg_temp_unc state Country
1496 1980-01-01    26.652         0.190  Acre  Brazil
1497 1980-02-01    26.495         0.495  Acre  Brazil
1498 1980-03-01    26.270         0.236  Acre  Brazil
1499 1980-04-01    26.430         0.201  Acre  Brazil
1500 1980-05-01    25.802         0.882  Acre  Brazil